services:
  mysql:
    image: mysql:8.4
    container_name: reservapro-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - ./crear-bases.sql:/docker-entrypoint-initdb.d/crear-bases.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  usuario:
    build: ./usuario
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ms-usuario?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    depends_on:
      mysql:
        condition: service_healthy

  reserva:
    build: ./reserva
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ms-reserva?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    depends_on:
      mysql:
        condition: service_healthy

  pago:
    build: ./pago
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ms-pago?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    depends_on:
      mysql:
        condition: service_healthy

  eureka:
    build: ./Eureka
    ports:
      - "8761:8761"

  gateway:
    build: ./gateway
    ports:
      - "8084:8084"
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "reservapro": {
            "routes": {
              "usuarios": "http://usuario:8081",
              "reservas": "http://reserva:8082",
              "pagos": "http://pago:8083",
            }
          }
        }
    depends_on:
      - usuario
      - reserva
      - pago