spring:
  application:
    name: gateway

server:
  port: 8084

reservapro:
  routes:
    usuarios: http://localhost:8081
    reservas: http://localhost:8082
    pagos: http://localhost:8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html
